<a href="https://colab.research.google.com/github/somilbansal11/Holographic-Microscopy/blob/main/matlab_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import mat73
data=mat73.loadmat('/content/drive/MyDrive/holo_dataset_256_73.mat')

In [ ]:
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
pip install mat73

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [5]:
import numpy as np

In [20]:
print(data)

{'holo': array([[[0.99975402, 0.99986789, 0.9997783 , ..., 0.99969221,
         1.00007804, 0.99975118],
        [1.00023457, 0.99975134, 1.00016681, ..., 1.00010557,
         1.00012646, 0.99978098],
        [1.00000252, 1.00009022, 1.00012196, ..., 1.0002577 ,
         0.99973897, 1.00011181],
        ...,
        [0.99980031, 0.9997618 , 1.00022352, ..., 0.99979692,
         1.00021191, 1.00023714],
        [0.99976572, 1.0001593 , 1.0000035 , ..., 1.00027927,
         0.99994819, 0.99998355],
        [1.00010675, 1.00019637, 0.99977843, ..., 1.0000475 ,
         0.99973323, 0.99978512]],

       [[1.00027463, 0.9997275 , 1.00017501, ..., 0.99997352,
         1.00018295, 0.99995144],
        [0.99987373, 0.9999593 , 1.00010945, ..., 1.00030523,
         0.99972652, 1.00025855],
        [0.99985538, 1.00026557, 0.99975811, ..., 0.99987758,
         1.00020828, 1.00020888],
        ...,
        [1.00027121, 0.99976002, 1.00002009, ..., 0.99973399,
         1.00003739, 0.99977315],
   

In [6]:
l=4000
X_train = np.zeros(shape=[l,256, 256,1])
Y_train = np.zeros(shape = [l,3])

In [7]:
o=2000

In [8]:
X_test = np.zeros(shape=[o,256, 256,1])
Y_test = np.zeros(shape = [o,3])

In [9]:
print(Y_test)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
k=range(0,4000)

In [11]:
m=range(0,2000)

In [18]:
data['x_data']

array([174.00726588, 133.04810498, 180.25431511, ..., 141.39017487,
       199.58916055, 102.57540606])

In [12]:
for i in k:
    X_train[i,:,:,0]=(data['holo'][:,:,i])
    Y_train[i,0],Y_train[i,1],Y_train[i,2]=data['x_data'][i],data['y_data'][i],data['z_data'][i]

In [13]:
print(X_train)

[[[[0.99975402]
   [1.00023457]
   [1.00000252]
   ...
   [0.99980031]
   [0.99976572]
   [1.00010675]]

  [[1.00027463]
   [0.99987373]
   [0.99985538]
   ...
   [1.00027121]
   [1.00012838]
   [0.9997793 ]]

  [[0.99977835]
   [0.99997776]
   [1.00024705]
   ...
   [0.99972785]
   [1.00001458]
   [1.00027857]]

  ...

  [[1.0002978 ]
   [0.99987503]
   [0.99984248]
   ...
   [0.99969579]
   [1.00000887]
   [1.00030762]]

  [[1.00014043]
   [1.00013884]
   [0.99969902]
   ...
   [0.99986185]
   [1.00025042]
   [1.0002192 ]]

  [[0.99987309]
   [1.00029816]
   [0.99978662]
   ...
   [1.00013881]
   [1.00029653]
   [0.99995675]]]


 [[[0.99986789]
   [0.99975134]
   [1.00009022]
   ...
   [0.9997618 ]
   [1.0001593 ]
   [1.00019637]]

  [[0.9997275 ]
   [0.9999593 ]
   [1.00026557]
   ...
   [0.99976002]
   [0.99990302]
   [1.00026468]]

  [[0.99983229]
   [1.0002022 ]
   [1.00020158]
   ...
   [0.99997217]
   [0.99973509]
   [1.00009673]]

  ...

  [[0.99975166]
   [1.0000424 ]
   [1.0

In [14]:
for i in m:
    X_test[i,:,:,0]=(data['holo'][:,:,i])
    Y_test[i,0],Y_train[i,1],Y_train[i,2]=data['x_data'][i],data['y_data'][i],data['z_data'][i]

In [13]:

hp.show(X_train[5,:,:,0])

NameError: ignored

In [15]:
import tensorflow as tf;
from tensorflow.keras import layers;
from tensorflow.keras import Model;
from tensorflow.keras.callbacks import EarlyStopping

In [16]:
print(tensorflow.config.list_physical_devices('GPU'))

NameError: ignored

In [16]:
from keras.layers import BatchNormalization
import keras
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten
img_input = layers.Input(shape=(256, 256,1))
x = layers.Conv2D(16, 3, activation='relu', strides = 1, padding = 'same')(img_input)
x = BatchNormalization(axis=-1)(x)
x = layers.MaxPool2D(pool_size=2)(x)
x = layers.Conv2D(32, 3, activation='relu', strides = 2)(x)
x = layers.MaxPool2D(pool_size=2)(x)
x = BatchNormalization(axis=-1)(x)
x = layers.Conv2D(64, 3, activation='swish', strides = 2)(x)
x = layers.MaxPool2D(pool_size=2)(x)
x = BatchNormalization(axis=-1)(x)
x = layers.Flatten()(x)
x = layers.Dense(8, activation='swish')(x)
x = layers.Flatten()(x)
output = layers.Dense(3, activation='relu')(x)
model = Model(img_input, output)
model.summary()


Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 256, 256, 1)]     0         
                                                                 
 conv2d (Conv2D)             (None, 256, 256, 16)      160       
                                                                 
 batch_normalization (BatchN  (None, 256, 256, 16)     64        
 ormalization)                                                   
                                                                 
 max_pooling2d (MaxPooling2D  (None, 128, 128, 16)     0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 63, 63, 32)        4640      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 31, 31, 32)       0     

In [17]:
model.compile(optimizer='adam', loss='mean_squared_error')

In [18]:


# Train the model
history = model.fit(X_train, Y_train, epochs=10, batch_size=64)

# Evaluate the model on the test set
test_loss = model.evaluate(X_test, Y_test)

Epoch 1/10
63/63 [==============================] - 160s 3s/step - loss: 200495.8438
Epoch 2/10
63/63 [==============================] - 158s 3s/step - loss: 49141.1797
Epoch 3/10
63/63 [==============================] - 157s 2s/step - loss: 4579.5801
Epoch 4/10
63/63 [==============================] - 158s 3s/step - loss: 713.0755
Epoch 5/10
63/63 [==============================] - 157s 2s/step - loss: 301.5938
Epoch 6/10
63/63 [==============================] - 158s 3s/step - loss: 273.9107
Epoch 7/10
63/63 [==============================] - 160s 3s/step - loss: 213.4240
Epoch 8/10
63/63 [==============================] - 165s 3s/step - loss: 172.3345
Epoch 9/10
63/63 [==============================] - 157s 2s/step - loss: 169.2380
Epoch 10/10
63/63 [==============================] - 23s 355ms/step - loss: 648149.8750
